from __future__ import annotations

from datetime import UTC, datetime, timedelta

from app.domain.models import MarketQuote, OrderBookSnapshot, PriceLevel


def build_demo_quotes() -> list[MarketQuote]:
    now = datetime.now(UTC)
    return [
        MarketQuote(
            market_id="poly_btc_100k",
            event_id="evt_btc",
            slug="btc-100k",
            question="Will Bitcoin reach $100k before June 30?",
            category="crypto",
            related_group="btc-thresholds",
            expiry=now + timedelta(days=40),
            yes_token_id="yes_btc_100k",
            no_token_id="no_btc_100k",
            yes_price=0.47,
            no_price=0.48,
            yes_ask=0.47,
            no_ask=0.48,
            liquidity=6500,
            volume_24h=22000,
            recent_move=0.04,
        ),
        MarketQuote(
            market_id="poly_eth_etf",
            event_id="evt_eth",
            slug="eth-etf-approval",
            question="Will an ETH ETF launch before September 30?",
            category="crypto",
            related_group="eth-etf",
            expiry=now + timedelta(days=70),
            yes_token_id="yes_eth_etf",
            no_token_id="no_eth_etf",
            yes_price=0.53,
            no_price=0.51,
            yes_ask=0.53,
            no_ask=0.51,
            liquidity=4800,
            volume_24h=12000,
            recent_move=0.08,
        ),
        MarketQuote(
            market_id="poly_fed_cut_june",
            event_id="evt_fed",
            slug="fed-cut-june",
            question="Will the Fed cut rates by June meeting?",
            category="finance",
            related_group="fed-cuts-2026",
            expiry=now + timedelta(days=18),
            yes_token_id="yes_fed_cut_june",
            no_token_id="no_fed_cut_june",
            yes_price=0.38,
            no_price=0.60,
            yes_ask=0.39,
            no_ask=0.60,
            liquidity=3200,
            volume_24h=8100,
            recent_move=0.03,
        ),
        MarketQuote(
            market_id="poly_fed_cut_july",
            event_id="evt_fed",
            slug="fed-cut-july",
            question="Will the Fed cut rates by July meeting?",
            category="finance",
            related_group="fed-cuts-2026",
            expiry=now + timedelta(days=45),
            yes_token_id="yes_fed_cut_july",
            no_token_id="no_fed_cut_july",
            yes_price=0.54,
            no_price=0.43,
            yes_ask=0.55,
            no_ask=0.43,
            liquidity=3500,
            volume_24h=9200,
            recent_move=0.01,
        ),
        MarketQuote(
            market_id="poly_weather_heatwave",
            event_id="evt_weather",
            slug="heatwave-cph",
            question="Will Copenhagen hit 30C next week?",
            category="weather",
            related_group="copenhagen-weather",
            expiry=now + timedelta(days=7),
            yes_token_id="yes_heatwave",
            no_token_id="no_heatwave",
            yes_price=0.42,
            no_price=0.58,
            yes_ask=0.42,
            no_ask=0.58,
            liquidity=400,
            volume_24h=300,
            recent_move=0.09,
            last_updated=now - timedelta(seconds=60),
        ),
    ]


def build_demo_books() -> dict[str, OrderBookSnapshot]:
    now = datetime.now(UTC)
    stale_time = now - timedelta(seconds=60)
    return {
        "poly_btc_100k:yes": OrderBookSnapshot(
            market_id="poly_btc_100k",
            token_id="yes_btc_100k",
            outcome="yes",
            timestamp=now,
            asks=[PriceLevel(price=0.47, size=80), PriceLevel(price=0.48, size=200)],
            bids=[PriceLevel(price=0.46, size=120)],
            last_trade_price=0.47,
        ),
        "poly_btc_100k:no": OrderBookSnapshot(
            market_id="poly_btc_100k",
            token_id="no_btc_100k",
            outcome="no",
            timestamp=now,
            asks=[PriceLevel(price=0.48, size=90), PriceLevel(price=0.49, size=180)],
            bids=[PriceLevel(price=0.47, size=100)],
            last_trade_price=0.48,
        ),
        "poly_eth_etf:yes": OrderBookSnapshot(
            market_id="poly_eth_etf",
            token_id="yes_eth_etf",
            outcome="yes",
            timestamp=now,
            asks=[PriceLevel(price=0.45, size=2), PriceLevel(price=0.54, size=80)],
            bids=[PriceLevel(price=0.44, size=10)],
            last_trade_price=0.53,
        ),
        "poly_eth_etf:no": OrderBookSnapshot(
            market_id="poly_eth_etf",
            token_id="no_eth_etf",
            outcome="no",
            timestamp=now,
            asks=[PriceLevel(price=0.49, size=2), PriceLevel(price=0.55, size=80)],
            bids=[PriceLevel(price=0.48, size=12)],
            last_trade_price=0.51,
        ),
        "poly_fed_cut_june:yes": OrderBookSnapshot(
            market_id="poly_fed_cut_june",
            token_id="yes_fed_cut_june",
            outcome="yes",
            timestamp=now,
            asks=[PriceLevel(price=0.39, size=60)],
            bids=[PriceLevel(price=0.38, size=50)],
            last_trade_price=0.38,
        ),
        "poly_fed_cut_june:no": OrderBookSnapshot(
            market_id="poly_fed_cut_june",
            token_id="no_fed_cut_june",
            outcome="no",
            timestamp=now,
            asks=[PriceLevel(price=0.60, size=70)],
            bids=[PriceLevel(price=0.59, size=55)],
            last_trade_price=0.60,
        ),
        "poly_fed_cut_july:yes": OrderBookSnapshot(
            market_id="poly_fed_cut_july",
            token_id="yes_fed_cut_july",
            outcome="yes",
            timestamp=now,
            asks=[PriceLevel(price=0.55, size=70)],
            bids=[PriceLevel(price=0.54, size=70)],
            last_trade_price=0.54,
        ),
        "poly_fed_cut_july:no": OrderBookSnapshot(
            market_id="poly_fed_cut_july",
            token_id="no_fed_cut_july",
            outcome="no",
            timestamp=now,
            asks=[PriceLevel(price=0.43, size=80)],
            bids=[PriceLevel(price=0.42, size=80)],
            last_trade_price=0.43,
        ),
        "poly_weather_heatwave:yes": OrderBookSnapshot(
            market_id="poly_weather_heatwave",
            token_id="yes_heatwave",
            outcome="yes",
            timestamp=stale_time,
            asks=[PriceLevel(price=0.42, size=15)],
            bids=[PriceLevel(price=0.40, size=10)],
            last_trade_price=0.42,
        ),
        "poly_weather_heatwave:no": OrderBookSnapshot(
            market_id="poly_weather_heatwave",
            token_id="no_heatwave",
            outcome="no",
            timestamp=stale_time,
            asks=[PriceLevel(price=0.58, size=15)],
            bids=[PriceLevel(price=0.56, size=10)],
            last_trade_price=0.58,
        ),
    }

